version: '3'
services:
  tmpfs_mysqldb:
    build: .
    privileged: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQLD_DATA_RAMDISK_SIZE_MB=1000
    ports:
      - "3306:3306"